export const CERTIFICATE_STATUS = Object.freeze({
  VALID: 'VALID',
  EXPIRED: 'EXPIRED',
  ABOUT_TO_EXPIRE: 'ABOUT_TO_EXPIRE',
});

export const CERTIFICATE_STATUS_COLORS = Object.freeze({
  VALID: '#34C38F',
  EXPIRED: '#F46A6A',
  ABOUT_TO_EXPIRE: '#F1B44C',
});
