export const DEVICES_PAGE_KEYS = {
  VIEW_MODE: '@DOJOT/DEVICES_PAGE_VIEW_MODE',
};

export const TEMPLATES_PAGE_KEYS = {
  VIEW_MODE: '@DOJOT/TEMPLATES_PAGE_VIEW_MODE',
};

export const TEMPLATE_ATTRIBUTES_PAGE_KEYS = {
  VIEW_MODE: '@DOJOT/TEMPLATE_ATTRIBUTES_PAGE_VIEW_MODE',
};

export const CERTIFICATION_AUTHORITIES_PAGE_KEYS = {
  VIEW_MODE: '@DOJOT/CERTIFICATION_AUTHORITIES_PAGE_VIEW_MODE',
};

export const CERTIFICATES_PAGE_KEYS = {
  VIEW_MODE: '@DOJOT/CERTIFICATES_PAGE_VIEW_MODE',
};

export const LANGUAGE_KEYS = {
  LANGUAGE: '@DOJOT/LANGUAGE',
};
