export const EVENT = Object.freeze({
    CHANGE_MENU: '@DOJOT/CHANGE_MENU',
    UPDATE_THEME: '@DOJOT/UPDATE_THEME',
    GLOBAL_TOAST: '@DOJOT/GLOBAL_TOAST',
    CHANGE_ROUTE: '@DOJOT/CHANGE_ROUTE',
});